# Text Mining - Introdução

In [4]:
!pip install nltk
!pip install spacy
!pip install transformers

Requirement already satisfied: nltk in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (3.8.2)
Requirement already satisfied: tqdm in /home/thiago/.local/lib/python3.8/site-packages (from nltk) (4.65.0)
Requirement already satisfied: click in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from nltk) (7.1.2)
Requirement already satisfied: joblib in /home/thiago/.local/lib/python3.8/site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /home/thiago/.local/lib/python3.8/site-packages (from nltk) (2022.4.24)
Requirement already satisfied: spacy in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (3.7.5)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /home/thiago/.local/lib/python3.8/site-packages (from spacy) (2.0.7)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /home/thiago/.local/lib/python3.8/site-packages (from spacy) (1.0.9)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /home/thiago/.local/lib/python3.8/site-packages (from spacy) (3.0.12)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /home/thiago/.local/lib/python3.8/site-packages (from spacy) (4.65.0)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /home/thiago/.local/lib/python3.8/site-packages (from spacy) (2.4.6)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from spacy) (0.4.1)
Requirement already satisfied: packaging>=20.0 in /home/thiago/.local/lib/python3.8/site-packages (from spacy) (21.3)
Requirement already satisfied: setuptools in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from spacy) (67.6.0)
Requirement already satisfied: numpy>=1.15.0 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from spacy) (1.24.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from spacy) (2.32.3)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from spacy) (8.2.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from spacy) (1.10.17)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /home/thiago/.local/lib/python3.8/site-packages (from spacy) (2.0.8)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /home/thiago/.local/lib/python3.8/site-packages (from spacy) (3.3.0)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /home/thiago/.local/lib/python3.8/site-packages (from spacy) (1.0.4)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /home/thiago/.local/lib/python3.8/site-packages (from spacy) (3.0.8)
Requirement already satisfied: jinja2 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from spacy) (3.1.2)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from spacy) (0.3.2)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /home/thiago/.local/lib/python3.8/site-packages (from spacy) (1.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/thiago/.local/lib/python3.8/site-packages (from packaging>=20.0->spacy) (2.4.7)
Requirement already satisfied: typing-extensions>=4.2.0 in /home/thiago/.local/lib/python3.8/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.19)
Requirement already satisfied: idna<4,>=2.5 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/thiago/.local/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.6.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/thiago/.local/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.12)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /home/thiago/.local/lib/python3.8/site-packages (from thinc<8.3.0,>=8.2.2->spacy) (0.7.9)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /home/thiago/.local/lib/python3.8/site-packages (from thinc<8.3.0,>=8.2.2->spacy) (0.0.4)
Requirement already satisfied: click<7.2.0,>=7.1.1 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from typer<1.0.0,>=0.3.0->spacy) (7.1.2)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.18.1)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /home/thiago/.local/lib/python3.8/site-packages (from weasel<0.5.0,>=0.1.0->spacy) (6.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from jinja2->spacy) (2.1.2)
Requirement already satisfied: transformers in /home/thiago/.local/lib/python3.8/site-packages (4.19.2)
Requirement already satisfied: requests in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from transformers) (2.32.3)
Requirement already satisfied: regex!=2019.12.17 in /home/thiago/.local/lib/python3.8/site-packages (from transformers) (2022.4.24)
Requirement already satisfied: numpy>=1.17 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from transformers) (1.24.2)
Requirement already satisfied: filelock in /home/thiago/.local/lib/python3.8/site-packages (from transformers) (3.7.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.13,>=0.11.1 in /home/thiago/.local/lib/python3.8/site-packages (from transformers) (0.12.1)
Requirement already satisfied: pyyaml>=5.1 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from transformers) (6.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in /home/thiago/.local/lib/python3.8/site-packages (from transformers) (0.6.0)
Requirement already satisfied: packaging>=20.0 in /home/thiago/.local/lib/python3.8/site-packages (from transformers) (21.3)
Requirement already satisfied: tqdm>=4.27 in /home/thiago/.local/lib/python3.8/site-packages (from transformers) (4.65.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/thiago/.local/lib/python3.8/site-packages (from huggingface-hub<1.0,>=0.1.0->transformers) (4.12.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/thiago/.local/lib/python3.8/site-packages (from packaging>=20.0->transformers) (2.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from requests->transformers) (1.26.19)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/thiago/.local/lib/python3.8/site-packages (from requests->transformers) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from requests->transformers) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/thiago/.local/lib/python3.8/site-packages (from requests->transformers) (2024.6.2)

In [5]:
import pandas as pd
import re
import nltk
import spacy
import string
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
## Ensure you have at least this data:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('vader_lexicon')
nltk.download('punkt_tab')

#You can install everything available by running this line
#nltk.download()

[nltk_data] Downloading package stopwords to /home/thiago/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/thiago/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/thiago/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/thiago/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

## Basic Pre-Processing with NLTK

#### Sentence separation

In [7]:
from nltk.tokenize import sent_tokenize

texto = "A fazenda é muito grande. O Dr. da Fazenda possui vários animais. Aqui temos um olho d'água."

sentencas = sent_tokenize(texto)

for sent in sentencas:
    print(sent)

A fazenda é muito grande.
O Dr. da Fazenda possui vários animais.
Aqui temos um olho d'água.

#### Tokenization

In [8]:
from nltk.tokenize import word_tokenize

texto = "A fazenda é muito grande. O Dr. da Fazenda possui vários animais. Aqui temos um olho d'água."

palavras = word_tokenize(texto) 

for palavra in palavras:
    print(palavra)

A
fazenda
é
muito
grande
.
O
Dr.
da
Fazenda
possui
vários
animais
.
Aqui
temos
um
olho
d'água
.

### Illustrating with Yelp review data

In [9]:
dfCharlotte= pd.read_csv("reviewsTestCharlotte.csv")

reviewsCharlotte_original = dfCharlotte['text']
reviewsCharlotte_original

reviewsCharlotte_original[0]

'I loved the customer service! Fast, but the doctor took her time to make sure I was happy in my contact lenses. Thank you!'

In [10]:
reviewsCharlotte_original.shape

(48617,)

#### Converting to lowercase

In [11]:
reviewsCharlotte_prep = reviewsCharlotte_original.str.lower()
reviewsCharlotte_prep

0        i loved the customer service! fast, but the do...
1        i've been coming here for a couple of years bu...
2        i really liked the optometrist here. the wait ...
3        robert and his team took great care of me when...
4        edit: i'm lowering this review from 5-stars to...
                               ...
48612    we've now had mike out twice to fix some leaks...
48613    love the new location lauren is always right o...
48614    i completely ruined my hair today attempting t...
48615    i have been going to lauren for years now and ...
48616    always available when i need her, lauren rocks...
Name: text, Length: 48617, dtype: object

#### Remove punctuation

In [12]:
PONTUACAO = string.punctuation

def remove_pontuacao(text):
    return text.translate(str.maketrans('', '', PONTUACAO))

reviewsCharlotte_prep = reviewsCharlotte_prep.apply(lambda text: remove_pontuacao(text))
reviewsCharlotte_prep

0        i loved the customer service fast but the doct...
1        ive been coming here for a couple of years but...
2        i really liked the optometrist here the wait w...
3        robert and his team took great care of me when...
4        edit im lowering this review from 5stars to 3s...
                               ...
48612    weve now had mike out twice to fix some leaks ...
48613    love the new location lauren is always right o...
48614    i completely ruined my hair today attempting t...
48615    i have been going to lauren for years now and ...
48616    always available when i need her lauren rocks ...
Name: text, Length: 48617, dtype: object

#### Remove stopwords

In [13]:
from nltk.corpus import stopwords

STOPWORDS = set(stopwords.words('english'))

def remove_stopwords(text):
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])

reviewsCharlotte_prep = reviewsCharlotte_prep.apply(lambda text: remove_stopwords(text))
print(reviewsCharlotte_prep)

print(STOPWORDS)

0        loved customer service fast doctor took time m...
1        ive coming couple years optometrist business b...
2        really liked optometrist wait little longer wo...
3        robert team took great care repairing car back...
4        edit im lowering review 5stars 3stars wrote or...
                               ...
48612    weve mike twice fix leaks pex pipes first time...
48613    love new location lauren always right point lo...
48614    completely ruined hair today attempting highli...
48615    going lauren years would never see another hai...
48616    always available need lauren rocks particular ...
Name: text, Length: 48617, dtype: object
{"needn't", "you'd", 'wasn', 'was', 'but', 'those', 'herself', 'yourselves', 'they', "isn't", "she'd", "it'll", "you're", 'them', "shouldn't", 'again', 'against', 'at', 'because', 'below', 'him', 'same', 'hers', "mustn't", 'will', 't', 'while', "wouldn't", "they're", 'had', 'through', 'ain', 's', 'won', 'its', "hasn't", 'down', 'is', 'isn', 'an', 'further', 're', 'both', 'mightn', 'my', 'so', 'or', 'if', 'once', 'are', "they've", 'during', 'has', "weren't", 'between', 'by', 'off', 'where', 'there', 'am', "i'd", 'only', 'have', 'these', 'not', "doesn't", "didn't", 'their', 'how', 'aren', 'she', 'very', "won't", 'under', 've', 'now', 'couldn', 'her', 'did', 'some', 'it', 'i', 'hasn', 'we', "mightn't", 'just', "we'll", 'wouldn', 'here', 'doing', 'doesn', "we're", "he'd", 'll', 'weren', 'for', "should've", 'any', 'all', 'and', 'each', "i've", 'what', 'theirs', 'this', 'y', "i'm", 'itself', "hadn't", 'shan', 'haven', 'over', 'myself', 'do', 'the', 'nor', 'whom', "she's", 'me', 'too', 'himself', 'few', "it's", 'm', 'ma', 'needn', 'ours', 'yours', 'than', 'who', 'having', "i'll", "that'll", 'up', "he's", "she'll", 'a', 'on', "it'd", 'above', "you'll", 'own', 'such', 'until', "they'd", "don't", "we'd", 'before', 'you', 'mustn', 'themselves', "couldn't", 'to', "shan't", 'didn', 'were', "aren't", 'don', 'most', 'been', "haven't", "we've", 'more', 'yourself', 'with', 'when', 'no', 'from', 'be', "they'll", 'o', 'why', 'should', 'as', 'being', "he'll", 'into', 'in', 'out', 'about', 'd', 'he', 'can', 'does', "you've", 'hadn', 'of', 'our', 'that', 'his', 'ourselves', 'then', 'your', "wasn't", 'shouldn', 'after', 'which', 'other'}

#### Stemming

In [14]:
from nltk.stem.porter import PorterStemmer

stemmer = PorterStemmer()

def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

reviewsCharlotte_prep= reviewsCharlotte_prep.apply(lambda text: stem_words(text))
reviewsCharlotte_prep

0        love custom servic fast doctor took time make ...
1        ive come coupl year optometrist busi busi yelp...
2        realli like optometrist wait littl longer woul...
3        robert team took great care repair car back ca...
4        edit im lower review 5star 3star wrote origin ...
                               ...
48612    weve mike twice fix leak pex pipe first time l...
48613    love new locat lauren alway right point love h...
48614    complet ruin hair today attempt highlight than...
48615    go lauren year would never see anoth hairdress...
48616    alway avail need lauren rock particular red ha...
Name: text, Length: 48617, dtype: object

# Topic Modeling

In [15]:
from gensim.models.ldamodel import LdaModel
from gensim.corpora.dictionary import Dictionary

### No preprocessing

In [16]:
dataset_orig = [d.split() for d in reviewsCharlotte_original]
dictionary_orig = Dictionary(dataset_orig)
corpus_orig = [dictionary_orig.doc2bow(doc) for doc in dataset_orig]

model_original =LdaModel(corpus=corpus_orig, id2word=dictionary_orig, num_topics=10, iterations=100, passes=5,random_state=1)

In [17]:
for i in  model_original.show_topics(num_topics=10, num_words=6, log=False):
    print(i)
    print('---')

(0, '0.023*"games" + 0.010*"cookies" + 0.009*"Asked" + 0.005*"Rooms" + 0.005*"delivered." + 0.004*"purpose"')
---
(1, '0.040*"I" + 0.036*"to" + 0.033*"the" + 0.020*"a" + 0.017*"you" + 0.016*"that"')
---
(2, '0.021*"massage" + 0.008*"Taste" + 0.006*"sake" + 0.006*"Still," + 0.005*"Suites" + 0.005*"Avoid"')
---
(3, '0.005*"Ice" + 0.004*"mold" + 0.004*"Awful" + 0.003*"pleasure." + 0.003*"this?" + 0.003*"Cesar"')
---
(4, '0.050*"the" + 0.040*"and" + 0.039*"was" + 0.030*"I" + 0.026*"a" + 0.016*"The"')
---
(5, '0.015*"Thai" + 0.015*"ribs" + 0.008*"tire" + 0.007*"pork," + 0.007*"Taco" + 0.006*"Fantastic"')
---
(6, '0.012*"Hall" + 0.010*"Western" + 0.004*"tipped" + 0.004*"Yeah," + 0.003*"watch." + 0.002*":)."')
---
(7, '0.045*"hair" + 0.020*"salon" + 0.011*"cut" + 0.010*"color" + 0.010*"polish" + 0.008*"pedicure"')
---
(8, '0.046*"the" + 0.043*"and" + 0.039*"a" + 0.029*"is" + 0.023*"to" + 0.021*"of"')
---
(9, '0.046*"the" + 0.044*"and" + 0.041*"to" + 0.040*"I" + 0.038*"was" + 0.022*"a"')
---

### With preprocessing

In [18]:
dataset_prep = [d.split() for d in reviewsCharlotte_prep]
dictionary_prep = Dictionary(dataset_prep)
corpus_prep = [dictionary_prep.doc2bow(doc) for doc in dataset_prep]

model_prep =LdaModel(corpus=corpus_prep, id2word=dictionary_prep, num_topics=10, iterations=100, passes=5,random_state=1)

In [19]:
for i in  model_prep.show_topics(num_topics=10, num_words=6, log=False):
    print(i)
    print('---')

(0, '0.024*"beer" + 0.014*"bar" + 0.013*"place" + 0.013*"great" + 0.012*"good" + 0.010*"nice"')
---
(1, '0.023*"order" + 0.023*"food" + 0.015*"time" + 0.015*"wait" + 0.014*"us" + 0.013*"minut"')
---
(2, '0.021*"breakfast" + 0.018*"coffe" + 0.017*"egg" + 0.017*"brunch" + 0.014*"ice" + 0.013*"cream"')
---
(3, '0.044*"great" + 0.035*"food" + 0.031*"place" + 0.025*"servic" + 0.019*"good" + 0.018*"love"')
---
(4, '0.022*"call" + 0.016*"would" + 0.012*"told" + 0.011*"custom" + 0.011*"said" + 0.010*"servic"')
---
(5, '0.043*"sub" + 0.027*"gift" + 0.023*"japanes" + 0.022*"groceri" + 0.021*"jerk" + 0.018*"fuel"')
---
(6, '0.020*"good" + 0.019*"burger" + 0.015*"chicken" + 0.014*"fri" + 0.014*"order" + 0.011*"like"')
---
(7, '0.016*"like" + 0.014*"get" + 0.012*"go" + 0.010*"im" + 0.010*"look" + 0.010*"place"')
---
(8, '0.123*"airport" + 0.083*"room" + 0.072*"hotel" + 0.053*"stay" + 0.050*"taco" + 0.030*"flight"')
---
(9, '0.015*"car" + 0.014*"help" + 0.011*"work" + 0.011*"store" + 0.010*"need" + 0.009*"staff"')
---

### Probabilities of topics in each document

In [20]:
docsProbabilities = model_prep.get_document_topics(corpus_prep, minimum_probability=0)

docsProbabilities

In [21]:
#Probability of each topic per document. Tuple (topic, probability)
for docDistribution in docsProbabilities[0:10]:
    print(docDistribution)

[(0, 0.0071519343), (1, 0.15872245), (2, 0.007151945), (3, 0.25934404), (4, 0.00715396), (5, 0.0071514593), (6, 0.007151999), (7, 0.007152517), (8, 0.0071514593), (9, 0.5318682)]
[(0, 0.0016159642), (1, 0.0016160049), (2, 0.0016156161), (3, 0.001615824), (4, 0.20321089), (5, 0.0016154525), (6, 0.1409837), (7, 0.001615989), (8, 0.0016155083), (9, 0.64449507)]
[(0, 0.001852898), (1, 0.00185335), (2, 0.0018526925), (3, 0.0018531331), (4, 0.0018529615), (5, 0.0018524572), (6, 0.0018528634), (7, 0.5231479), (8, 0.0018524554), (9, 0.46202928)]
[(0, 0.00294224), (1, 0.0029428527), (2, 0.0029422138), (3, 0.0029421574), (4, 0.11584241), (5, 0.0029418338), (6, 0.0029423486), (7, 0.0029422585), (8, 0.0029418422), (9, 0.86061984)]
[(0, 0.08094109), (1, 0.00048701806), (2, 0.00048694856), (3, 0.0004870454), (4, 0.5226361), (5, 0.005358452), (6, 0.029970376), (7, 0.00048702172), (8, 0.00048686858), (9, 0.35865906)]
[(0, 0.33742812), (1, 0.007703148), (2, 0.0077025583), (3, 0.31229982), (4, 0.007704205), (5, 0.007702004), (6, 0.007703077), (7, 0.0077030244), (8, 0.084665366), (9, 0.21938865)]
[(0, 0.00156635), (1, 0.0015663021), (2, 0.0015661189), (3, 0.0015664153), (4, 0.31293058), (5, 0.0015660233), (6, 0.0015662356), (7, 0.22381365), (8, 0.0015660231), (9, 0.45229232)]
[(0, 0.0023813616), (1, 0.0023816754), (2, 0.002381419), (3, 0.002381788), (4, 0.16609895), (5, 0.00238124), (6, 0.0023815678), (7, 0.002381521), (8, 0.0023812435), (9, 0.81484926)]
[(0, 0.282846), (1, 0.0012070352), (2, 0.0012067542), (3, 0.0012069045), (4, 0.36821643), (5, 0.013243909), (6, 0.0012067981), (7, 0.0012069877), (8, 0.0012066998), (9, 0.3284525)]
[(0, 0.0029450746), (1, 0.0029449915), (2, 0.00294481), (3, 0.0029451917), (4, 0.38797656), (5, 0.002944639), (6, 0.002945068), (7, 0.0029451821), (8, 0.0029446434), (9, 0.58846384)]

## Bertopic

In [22]:
!pip install bertopic

Requirement already satisfied: bertopic in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (0.16.4)
Requirement already satisfied: umap-learn>=0.5.0 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from bertopic) (0.5.7)
Requirement already satisfied: plotly>=4.7.0 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from bertopic) (6.0.1)
Requirement already satisfied: pandas>=1.1.5 in /home/thiago/.local/lib/python3.8/site-packages (from bertopic) (2.0.3)
Requirement already satisfied: scikit-learn>=0.22.2.post1 in /home/thiago/.local/lib/python3.8/site-packages (from bertopic) (1.3.2)
Requirement already satisfied: numpy>=1.20.0 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from bertopic) (1.24.2)
Requirement already satisfied: sentence-transformers>=0.4.1 in /home/thiago/.local/lib/python3.8/site-packages (from bertopic) (2.2.2)
Requirement already satisfied: tqdm>=4.41.1 in /home/thiago/.local/lib/python3.8/site-packages (from bertopic) (4.65.0)
Requirement already satisfied: hdbscan>=0.8.29 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from bertopic) (0.8.40)
Requirement already satisfied: joblib>=1.0 in /home/thiago/.local/lib/python3.8/site-packages (from hdbscan>=0.8.29->bertopic) (1.2.0)
Requirement already satisfied: scipy>=1.0 in /home/thiago/.local/lib/python3.8/site-packages (from hdbscan>=0.8.29->bertopic) (1.10.1)
Requirement already satisfied: pytz>=2020.1 in /home/thiago/.local/lib/python3.8/site-packages (from pandas>=1.1.5->bertopic) (2021.1)
Requirement already satisfied: tzdata>=2022.1 in /home/thiago/.local/lib/python3.8/site-packages (from pandas>=1.1.5->bertopic) (2024.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/thiago/.local/lib/python3.8/site-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: narwhals>=1.15.1 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from plotly>=4.7.0->bertopic) (1.35.0)
Requirement already satisfied: packaging in /home/thiago/.local/lib/python3.8/site-packages (from plotly>=4.7.0->bertopic) (21.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/thiago/.local/lib/python3.8/site-packages (from scikit-learn>=0.22.2.post1->bertopic) (3.1.0)
Requirement already satisfied: huggingface-hub>=0.4.0 in /home/thiago/.local/lib/python3.8/site-packages (from sentence-transformers>=0.4.1->bertopic) (0.6.0)
Requirement already satisfied: torchvision in /home/thiago/.local/lib/python3.8/site-packages (from sentence-transformers>=0.4.1->bertopic) (0.12.0)
Requirement already satisfied: nltk in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from sentence-transformers>=0.4.1->bertopic) (3.8.2)
Requirement already satisfied: transformers<5.0.0,>=4.6.0 in /home/thiago/.local/lib/python3.8/site-packages (from sentence-transformers>=0.4.1->bertopic) (4.19.2)
Requirement already satisfied: sentencepiece in /home/thiago/.local/lib/python3.8/site-packages (from sentence-transformers>=0.4.1->bertopic) (0.1.96)
Requirement already satisfied: torch>=1.6.0 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from sentence-transformers>=0.4.1->bertopic) (1.11.0)
Requirement already satisfied: numba>=0.51.2 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from umap-learn>=0.5.0->bertopic) (0.58.1)
Requirement already satisfied: pynndescent>=0.5 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from umap-learn>=0.5.0->bertopic) (0.5.13)
Requirement already satisfied: requests in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/thiago/.local/lib/python3.8/site-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (4.12.2)
Requirement already satisfied: pyyaml in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (6.0)
Requirement already satisfied: filelock in /home/thiago/.local/lib/python3.8/site-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (3.7.0)
Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from numba>=0.51.2->umap-learn>=0.5.0->bertopic) (0.41.1)
Requirement already satisfied: importlib-metadata in /home/thiago/.local/lib/python3.8/site-packages (from numba>=0.51.2->umap-learn>=0.5.0->bertopic) (4.8.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/thiago/.local/lib/python3.8/site-packages (from packaging->plotly>=4.7.0->bertopic) (2.4.7)
Requirement already satisfied: six>=1.5 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.16.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.13,>=0.11.1 in /home/thiago/.local/lib/python3.8/site-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers>=0.4.1->bertopic) (0.12.1)
Requirement already satisfied: regex!=2019.12.17 in /home/thiago/.local/lib/python3.8/site-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers>=0.4.1->bertopic) (2022.4.24)
Requirement already satisfied: click in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from nltk->sentence-transformers>=0.4.1->bertopic) (7.1.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from torchvision->sentence-transformers>=0.4.1->bertopic) (9.4.0)
Requirement already satisfied: zipp>=0.5 in /home/thiago/.local/lib/python3.8/site-packages (from importlib-metadata->numba>=0.51.2->umap-learn>=0.5.0->bertopic) (3.8.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/thiago/.local/lib/python3.8/site-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/thiago/.local/lib/python3.8/site-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (2024.6.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (1.26.19)

In [23]:
from bertopic import BERTopic

topic_model = BERTopic()

dataset_orig_list = [d for d in reviewsCharlotte_original]
dataset_orig_list

topics, probs = topic_model.fit_transform(dataset_orig_list)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [24]:
#Topics labeled as -1 are considered outliers
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,20427,-1_was_the_and_we,"[was, the, and, we, it, food, were, to, had, but]",[Just okay. My fiancé and I are new to town so...
1,0,1177,0_burger_fries_burgers_potato,"[burger, fries, burgers, potato, pickles, bun,...","[Their sign boasting ""Charlotte's Best Burgers..."
2,1,883,1_bbq_pork_brisket_ribs,"[bbq, pork, brisket, ribs, pulled, barbecue, m...",[I went to lunch at Bill Spoon's Barbecue on a...
3,2,581,2_coffee_starbucks_latte_mugs,"[coffee, starbucks, latte, mugs, shop, wifi, b...",[The best Starbucks in town. I love it here. B...
4,3,570,3_brunch_buffet_sunday_toast,"[brunch, buffet, sunday, toast, bistro, eggs, ...",[This place's brunch is amazing.\n\nWe went fo...
...,...,...,...,...,...
417,416,10,416_zoom_obedience_agility_dog,"[zoom, obedience, agility, dog, training, jule...",[update-I decided to give zoom room another ch...
418,417,10,417_latin_honduran_english_authentic,"[latin, honduran, english, authentic, salvador...",[Best latin food ever and really cheap. It's a...
419,418,10,418_bento_sushi_bentos_buffet,"[bento, sushi, bentos, buffet, rice, tofu, unc...",[Bento is definitely a unique place from what ...
420,419,10,419_blaze_pizza_lemonade_toppings,"[blaze, pizza, lemonade, toppings, preservativ...",[Of all the chain pizzerias I have to go with ...
421,420,10,420_drinks_bartender_bartenders_chain,"[drinks, bartender, bartenders, chain, placest...",[Was looking for a mid-level restaurant bar be...

##### Fine tuning

In [25]:
from bertopic.representation import KeyBERTInspired

representation_model = KeyBERTInspired()
topic_model_fine = BERTopic(representation_model=representation_model)

topics, probs = topic_model_fine.fit_transform(dataset_orig_list)

In [26]:
#Topics labeled as -1 are considered outliers
topic_model_fine.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,20143,-1_restaurant_pizza_food_delicious,"[restaurant, pizza, food, delicious, chicken, ...",[Our night out at Jade with friends for a holi...
1,0,909,0_barbecue_bbq_brisket_ribs,"[barbecue, bbq, brisket, ribs, barbeque, pork,...",[Came into town for a work related conference ...
2,1,834,1_burger_burgers_cheeseburger_fries,"[burger, burgers, cheeseburger, fries, patties...",[Smashburger was a nice little surprise. Havi...
3,2,822,2_hotel_hotels_marriott_rooms,"[hotel, hotels, marriott, rooms, hilton, inn, ...",[TRAVELERS BEWARE! If 0 stars was an option fo...
4,3,594,3_brunch_buffet_restaurant_dishes,"[brunch, buffet, restaurant, dishes, dinner, b...",[So after reading many stellar reviews about t...
...,...,...,...,...,...
399,398,10,398_shirts_shirt_tshirts_tshirt,"[shirts, shirt, tshirts, tshirt, clothes, ward...","[Great design help, pricing was very reasonabl..."
400,399,10,399_midtown_place_breezeway_town,"[midtown, place, breezeway, town, tavern, geor...",[I love this place they are so cool and they a...
401,400,10,400_oysters_oyster_charlotte_seafood,"[oysters, oyster, charlotte, seafood, coast, s...",[This place has some of the freshest seafood i...
402,401,10,401_bentos_sushi_bento_buffet,"[bentos, sushi, bento, buffet, entrees, meals,...","[So, we thought that this place would excel in..."
403,402,10,402_haircut_haircuts_salon_trim,"[haircut, haircuts, salon, trim, hair, hairsty...",[This was my son's second haircut. He is 15 m...

# Sentiment Analysis

### Using VADER

In [27]:
from nltk.sentiment import SentimentIntensityAnalyzer

sent = SentimentIntensityAnalyzer()

print(sent.polarity_scores("Yes! Data mining is very powerful!"))

{'neg': 0.0, 'neu': 0.385, 'pos': 0.615, 'compound': 0.7489}

The compound score is calculated in such a way that it represents the polarity of -1 to 1, where +1 is the most positive and -1 is the most negative.

### Using Textblob

In [28]:
!pip install -U textblob

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Requirement already satisfied: textblob in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (0.18.0.post0)
Requirement already satisfied: nltk>=3.8 in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from textblob) (3.8.2)
Requirement already satisfied: tqdm in /home/thiago/.local/lib/python3.8/site-packages (from nltk>=3.8->textblob) (4.65.0)
Requirement already satisfied: click in /home/thiago/anaconda3/envs/cursodm/lib/python3.8/site-packages (from nltk>=3.8->textblob) (7.1.2)
Requirement already satisfied: regex>=2021.8.3 in /home/thiago/.local/lib/python3.8/site-packages (from nltk>=3.8->textblob) (2022.4.24)
Requirement already satisfied: joblib in /home/thiago/.local/lib/python3.8/site-packages (from nltk>=3.8->textblob) (1.2.0)

In [ ]:
from textblob import TextBlob

frase = TextBlob("Yes! Data mining is very powerful!")
frase.sentiment
#range -1 to 1

Sentiment(polarity=0.48750000000000004, subjectivity=1.0)

##### With transformers

In [ ]:
from transformers import pipeline

# Load a sentiment analysis pipeline
sentiment_pipeline = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")

# Analyze text
result = sentiment_pipeline("Yes! Data mining is very powerful!")
print(result)

#probabilidade de estar associado a uma classe: 0.99 = elevada confiança

[{'label': 'POSITIVE', 'score': 0.9998205304145813}]

### Example with Yelp reviews

In [30]:
def verifica_MuitoPositivo(review):
    
    return sent.polarity_scores(review)["compound"] > 0.8


for review in reviewsCharlotte_original[0:10]:
    
    if verifica_MuitoPositivo(review):
        print(review)
        print('----')

I loved the customer service! Fast, but the doctor took her time to make sure I was happy in my contact lenses. Thank you!
----
Robert and his team took great care of me when repairing my car back up camera. The team was able to identify the issue and resolve it for a low cost option. The team could have taken advantage of me and oversold equipment that wasn't needed, however they were very upfront about the root cause of the issue and I was very pleased with the repair and the repair cost !
----
Edit: I'm lowering this review from 5-stars to 3-stars.  I wrote the original review prematurely. After having been around inside my car a bit I have noticed broken rivets & clips and pieces of carpet were never put back where they should have been. Also, many leftover pieces of wire and debris were left in the crevices and sides of the seat. My biggest issue is every time I turn my car on I hear a pop come from the JL subwoofer that was bought and installed at Freeman's. I brought this up to Joel (manager) and he told me to turn my stereo off before I turn the car off but the pop just returned when I turn the stereo on. I'm having to get these issues fixed elsewhere. Other than what I just mentioned everything else was done well and done just as I had requested.


______________________________________________
I would recommend Freeman's to anyone. I worked with Joel during my experience there and he was very helpful and a straight shooter with me.

I called in one day and spoke to him about my issue and he briefly discussed over the phone then told me to come into to discuss further. I drove up there and he explained and demonstrated the difference of sound with various equipment. This was very helpful and informative in my decision of what equipment I was going to need.

I had him make me up a quote, everything was priced great. I compared his pricing with online retailers. His original quote contained the same price for the sub on Crutchfield. Then I spoke to him again and I asked him to match Crutchfield price for the amplifier and he was able to go lower than Crutchfield.  Install price was very very reasonable compared to a few other places I looked up. My total invoice when I paid came in $5 less than my quote which I was very pleased about, no extra nonsense added later.

Install was great. I had a few minor requests which Joel didn't hesitate to tell me they could accomplish. I didn't notice any broken parts of anything from installation. Everything looks like it did when I dropped my car off, except when you turn up the volume! Sounded exactly the way I had described to Joel what I was looking for.

One of my favorite parts was the bass control knob placement. I had only expected it to be up under the dash, but what they did was awesome. They were able to place it on the center console of my Jeep Wrangler in a vacant spot under the arm rest that makes it look as if the knob was OEM. Such a cool added feature and I've realized how much more convenient it is.

Again, I would recommend Freeman's.
----
Jason and Roger provided excellent service...and they're very military friendly. I would definitely return. Thank you gentlemen!
----
I had a back up camera installed and it was the smoothest, cleanest deal I've ever made!  Robert was quick to return my initial call with very concise information regarding the equipment needed and the exact costs to perform the installation.  I took the car in at the time arranged and several hours later I was called to pick it up.  It works perfectly!

I am happy with the equipment, the service and the professional manner in which the entire deal was made and executed!
----

# Transformers - Similar phrases with sBert

In [31]:
#!pip install -U sentence-transformers
from sentence_transformers import SentenceTransformer, util

model_RobLarge = SentenceTransformer('all-MiniLM-L6-v2', device='cuda')

In [32]:
dfTweetsTrump = pd.read_csv("tweets_trump.csv")

#Using only with the first 10000 -
embeddingsTweets_ROBbase = model_RobLarge.encode(dfTweetsTrump.loc[0:10000,'text'], convert_to_tensor=True)

In [33]:
embeddingsTweets_ROBbase
matSimi = cosine_similarity(embeddingsTweets_ROBbase.cpu().detach().numpy())

In [34]:
maior = 0
count = 0
docID = -1
docTarget = 120

for i in matSimi[docTarget,:]:
    if count == docTarget:
        count +=1
        continue
        
    if i> maior:
        maior = i
        docID = count
    
    count+=1

In [35]:
print('****target***')
print(dfTweetsTrump.loc[docTarget,'text'])
print()
print("*** mais similar ***")
print(dfTweetsTrump.loc[docID,'text'])

print(maior)
print(docID)

****target***
RT @Claire_FOX5: #BREAKING:  @GaSecofState's office confirms Floyd County has found 2,600 ballots during audit.  Says Sec. Raffensperger wa…

*** mais similar ***
Investigators Dispatched After Fulton County Discovers ‘Issue‘ with Ballot Reporting https://t.co/lShmKksQ0O via @BreitbartNews
0.6110223
2582

## Other examples with Transformers

### Classification - zero-shot

In [36]:
from transformers import pipeline

classifier = pipeline("zero-shot-classification", model='valhalla/distilbart-mnli-12-1')

In [37]:
classifier(
    ["This is the Data Mining course from CPGEI",
     "I have a very good stock option, gonna be rich!"],
    
    candidate_labels=["education", "politics", "finance", "computer", "transport"],
)

[{'sequence': 'This is the Data Mining course from CPGEI',
  'labels': ['computer', 'education', 'transport', 'finance', 'politics'],
  'scores': [0.5107241272926331,
   0.33712857961654663,
   0.05968839302659035,
   0.05526594817638397,
   0.03719286620616913]},
 {'sequence': 'I have a very good stock option, gonna be rich!',
  'labels': ['finance', 'transport', 'computer', 'education', 'politics'],
  'scores': [0.8379274010658264,
   0.05080162733793259,
   0.04393560066819191,
   0.04384589567780495,
   0.023489370942115784]}]

### NER - Named Entity Recognition

In [38]:
from transformers import pipeline


#usando o modelo padrão 'dbmdz/bert-large-cased-finetuned-conll03-english' (podemos especificar outros)
ner = pipeline("ner", grouped_entities="simple")

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english)

In [39]:
ner("I am Thiago and a teach Data Mining at CPGEI.")

[{'entity_group': 'PER',
  'score': 0.9912441,
  'word': 'Thiago',
  'start': 5,
  'end': 11},
 {'entity_group': 'ORG',
  'score': 0.9959862,
  'word': 'CPGEI',
  'start': 39,
  'end': 44}]

In [40]:
## examples of transformers: https://huggingface.co/models

In [41]:
## spacy transformers: https://spacy.io/usage/embeddings-transformers#transformers